### ISSUE TITLE
breaking changes from 1.x -> 2.x regarding PVC use not well documented (how to make it work on 2.x?)

### ISSUE THREAD

**Issue by ppenguin** [utkuozdemir/helm-charts#11]
After upgrading my standard PVC defined like this (in `values.yaml`):

```yaml
persistence:
  data:
    enabled: true
    existingClaim: pvc-nfs-microserv-bt
```

stopped working (now simply `/data` is not custom-mounted), and I couldn't find out how to make it work under 2.x.

Any ideas?
