### ISSUE TITLE
Add possibility to mount hostpath to rootdir

### ISSUE THREAD

**Issue by armandleopold** [utkuozdemir/helm-charts#6]
Hello i need to apply this configuration : 

```yaml
        - name: rootdir
          hostPath:
            path: /var/data
            type: Directory
```

I had to fetch the helm and install locally, possible to integrate this feature ?
